#!/bin/sh

# This script is executed after the main build but before the image is generated.

set -e

# The path to our grub.cfg, relative from the Buildroot source directory
GRUB_CFG_SRC="../../board/weno-arm64/grub.cfg"

# Create the EFI boot directory
mkdir -p "${BINARIES_DIR}/efi/boot"

# Copy the GRUB config
cp "${GRUB_CFG_SRC}" "${BINARIES_DIR}/efi/boot/grub.cfg"

# Copy the GRUB EFI bootloader (generated by BR2_TARGET_GRUB2_ARM64_EFI)
if [ -f "${BINARIES_DIR}/grub.efi" ]; then
    cp "${BINARIES_DIR}/grub.efi" "${BINARIES_DIR}/efi/boot/bootaa64.efi"
else
    echo "WARNING: grub.efi not found at ${BINARIES_DIR}/grub.efi"
    echo "Available files in BINARIES_DIR:"
    ls -la "${BINARIES_DIR}" || true
fi