#!/bin/sh

set -e

# Create boot directory structure for genimage
mkdir -p "${BINARIES_DIR}/efi/boot"

# Copy kernel
if [ -f "${BINARIES_DIR}/Image" ]; then
    cp "${BINARIES_DIR}/Image" "${BINARIES_DIR}/Image"
    echo "Copied kernel image"
fi

# Copy the GRUB config
GRUB_CFG_SRC="../../board/weno-arm64/grub.cfg"
cp "${GRUB_CFG_SRC}" "${BINARIES_DIR}/efi/boot/grub.cfg"
echo "Copied grub.cfg"

# Copy the GRUB EFI bootloader (generated by BR2_TARGET_GRUB2_ARM64_EFI)
if [ -f "${BINARIES_DIR}/grub.efi" ]; then
    cp "${BINARIES_DIR}/grub.efi" "${BINARIES_DIR}/efi/boot/bootaa64.efi"
    echo "Copied bootaa64.efi"
else
    echo "WARNING: grub.efi not found at ${BINARIES_DIR}/grub.efi"
    ls -la "${BINARIES_DIR}" | grep -i grub || true
fi

echo "Post-build script completed"