#!/bin/sh

# S99acrylic_ui - Startup script for the Acrylic OS Kiosk UI

XORG_BIN=/usr/bin/Xorg
XSOCKET=/tmp/.X11-unix/X0

start_xorg_if_needed() {
    if [ -S "$XSOCKET" ]; then
        return 0
    fi

    if [ -x "$XORG_BIN" ]; then
        echo "Starting Xorg..."
        start-stop-daemon -S -q -b -m -p /var/run/xorg.pid --exec "$XORG_BIN" -- :0.0 vt01 -s 0 -noreset -allowMouseOpenFail
    else
        echo "Error: Xorg is not installed."
        return 1
    fi

    i=0
    while [ ! -S "$XSOCKET" ] && [ "$i" -lt 20 ]; do
        sleep 1
        i=$((i + 1))
    done

    if [ ! -S "$XSOCKET" ]; then
        echo "Error: Xorg did not start."
        return 1
    fi

    return 0
}

case "$1" in
    start)
        echo "Starting Acrylic OS Kiosk..."
        if start_xorg_if_needed; then
            export DISPLAY=:0.0
            /usr/bin/acrylic-ui-start &
        fi
        ;;
    stop)
        # We don't really have a stop mechanism for this simple kiosk
        echo "Stopping Acrylic OS Kiosk is not supported."
        ;;
    restart|reload)
        # Restarting would just be a reboot in this environment
        echo "Restarting Acrylic OS Kiosk is not supported."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
