#!/bin/sh

# S99weno_ui - Startup script for the Weno Kiosk UI

case "$1" in
    start)
        echo "Starting Weno UI Kiosk..."
        # Start the X server on display :0, in the background
        /usr/bin/xinit /usr/bin/weno-ui-start -- :0 &
        ;;
    stop)
        # We don't really have a stop mechanism for this simple kiosk
        echo "Stopping Weno UI Kiosk is not supported."
        ;;
    restart|reload)
        # Restarting would just be a reboot in this environment
        echo "Restarting Weno UI Kiosk is not supported."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
